### PR TITLE
Create a workflow that checks if there are any warnings

### PR DESCRIPTION
**Pull request by stoftot**

### CODE REVIEW

**Comment by stoftot** [comment]
Now this is interesting, it works sort of, it publish comment, but dosent find any warnings, which it should :(

**Review by math045b — CHANGES_REQUESTED** [review]
When successful I think it would be better if it says "NO WARNINGS AND ERRORS - SUCCESS!" or something similar

**Comment by stoftot** [comment]
> When successful I think it would be better if it says "NO WARNINGS AND ERRORS - SUCCESS!" or something similar

This is a good idea, I will take a look at it

**Comment by stoftot** [comment]
I know too little to try and incorporate, the workflow from marketplace, which is designed for c/c++.
Therefore, I'm just going to switch to a simpler implementation where the workflow fails if there are warnings

**Review by math045b — APPROVED** [review]

**Pull request merged**
